### ISSUE TITLE
ios 10 support

### ISSUE THREAD

**Issue by daniel-bluesea** [lyonanderson/iOS-Diagnostics#4]
is it working also for ios 10?

it seems that apple changed the private framework which has the power logs "api"

**Comment by ScottRobbins** [comment]
No. It seems they are using certificate pinning, so you can't mitm it.

**Comment by antwerpenR** [comment]
@lyonanderson 
Hello - seems not to be working for iOS 10 (on my iphone 6) - though it runs in the simulator.  Tracing it, I see that loadPowerLogs fails.  Seems to fail here:
`    NSBundle *b = [NSBundle bundleWithPath:@"/System/Library/PrivateFrameworks/iOSDiagnosticsSupport.framework"];

BOOL hasLoaded = [b load];
`

From what I can see by poking around a bit more.  It seems that "iOSDiagnosticsSupport.framework" no longer exists but there is: "DiagnosticsSupport.framework"...and changing the name in the code allows the bundle to be loaded but it then fails in the code that follows... It seems that the class MBSDevice is no longer present...  What are your ideas or knowledge on why this now fails and is there any way to fix it?
